name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-title-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PR Title Checker
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.event.pull_request.title }}
          config-file: .github/pr-title-checker-config.json
